server:
  port: 8080

app:
  frontend:
    base-url: ${FRONT_BASE_URL}

mydata:
  base-url: ${MOCKOON_API}

spring:
  application:
    name: MyAsset

#  profiles:
#    active: local # local / prod

  config:
    import:
      - application-security.yml
      - application-jwt.yml
      - application-db.yml
      - application-batch.yml
      - env.yml

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
