package dev.es.myasset.domain.budget;

import dev.es.myasset.domain.category.Category;
import dev.es.myasset.domain.shared.BaseEntity;
import dev.es.myasset.domain.user.User;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
@Table(name = "budget")
public class Budget extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long budgetId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_key", nullable = false)
    private User user;

    private Integer year;

    private Integer month;

    private boolean isAutoGenerated;    // 26-1-21 to-do : notification_rule 처럼 나눌것인지 아니면 다른 방법이 있는지 고민, 요구사항보충 그에 따른 도메인모델 정정

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cgy_id", nullable = true)
    private Category category;

    private BigDecimal amt;

}
